spring:
  application:
    name: News-Sseuk
  datasource:
    url: jdbc:mysql://localhost:3306/news-sseuk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 8082