spring:
  application:
    name: News-Sseuk
  datasource:
    #url: jdbc:mysql://localhost:3306/news-sseuk?createDatabaseIfNotExist=TRUE&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: root
    #password: dlrkgus1^^
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${MONGO_LOCAL}
    redis:
      host: ${REDIS_HOST}
      port: 6379
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  jwt:
    secret: ${SECRET_KEY}
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_SECRET_ID}
            redirect-uri: "http://localhost:8082/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name,email
            client-name: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
chrome:
  driver:
    path: ${CHROME_DRIVER}

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 8082

news:
  urls:
    - "https://news.naver.com/breakingnews/section/100/264"
    - "https://news.naver.com/breakingnews/section/100/265"
    - "https://news.naver.com/breakingnews/section/100/266"
    - "https://news.naver.com/breakingnews/section/100/267"
    - "https://news.naver.com/breakingnews/section/100/268"
    - "https://news.naver.com/breakingnews/section/100/269"
    - "https://news.naver.com/breakingnews/section/101/258"
    - "https://news.naver.com/breakingnews/section/101/259"
    - "https://news.naver.com/breakingnews/section/101/260"
    - "https://news.naver.com/breakingnews/section/101/261"
    - "https://news.naver.com/breakingnews/section/101/262"
    - "https://news.naver.com/breakingnews/section/101/263"
    - "https://news.naver.com/breakingnews/section/101/310"
    - "https://news.naver.com/breakingnews/section/101/771"
    - "https://news.naver.com/breakingnews/section/102/249"
    - "https://news.naver.com/breakingnews/section/102/250"
    - "https://news.naver.com/breakingnews/section/102/251"
    - "https://news.naver.com/breakingnews/section/102/252"
    - "https://news.naver.com/breakingnews/section/102/254"
    - "https://news.naver.com/breakingnews/section/102/255"
    - "https://news.naver.com/breakingnews/section/102/256"
    - "https://news.naver.com/breakingnews/section/102/257"
    - "https://news.naver.com/breakingnews/section/102/276"
    - "https://news.naver.com/breakingnews/section/102/59b"
    - "https://news.naver.com/breakingnews/section/103/237"
    - "https://news.naver.com/breakingnews/section/103/238"
    - "https://news.naver.com/breakingnews/section/103/239"
    - "https://news.naver.com/breakingnews/section/103/240"
    - "https://news.naver.com/breakingnews/section/103/241"
    - "https://news.naver.com/breakingnews/section/103/242"
    - "https://news.naver.com/breakingnews/section/103/243"
    - "https://news.naver.com/breakingnews/section/103/244"
    - "https://news.naver.com/breakingnews/section/103/245"
    - "https://news.naver.com/breakingnews/section/103/248"
    - "https://news.naver.com/breakingnews/section/103/376"
    - "https://news.naver.com/breakingnews/section/104/231"
    - "https://news.naver.com/breakingnews/section/104/232"
    - "https://news.naver.com/breakingnews/section/104/233"
    - "https://news.naver.com/breakingnews/section/104/234"
    - "https://news.naver.com/breakingnews/section/104/322"
    - "https://news.naver.com/breakingnews/section/105/226"
    - "https://news.naver.com/breakingnews/section/105/227"
    - "https://news.naver.com/breakingnews/section/105/228"
    - "https://news.naver.com/breakingnews/section/105/229"
    - "https://news.naver.com/breakingnews/section/105/230"
    - "https://news.naver.com/breakingnews/section/105/283"
    #- "https://news.naver.com/breakingnews/section/105/731"
    - "https://news.naver.com/breakingnews/section/105/732"