spring:
  application:
    name: News-Sseuk
  datasource:
    url: jdbc:mysql://localhost:3306/news-sseuk
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb+srv://sunshineonmyneck:dlrkgus1^^@cluster0.2xoy3j8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: crawling-articles
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 8080