spring:
  application:
    name: News-Sseuk
  datasource:
    url: jdbc:mysql://localhost:3306/news-sseuk?createDatabaseIfNotExist=TRUE&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ArticleDB
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  jwt:
    secret: ${SECRET_KEY}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_SECRET_ID}
            redirect-uri: "http://localhost:8082/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name,email
            client-name: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 8082